src/clients/kanbanClient.ts, src/infrastructures/createKanbanRepository.ts, src/infrastructures/createKanbanService.ts, src/infrastructures/createNotionKanbanClient.ts, src/repositories/kanbanRepository.ts
=> 🩹 100개 제한 안 걸리도록 픽스

src/infrastructures/createKanbanService.ts, src/infrastructures/createNotionKanbanClient.ts
=> 🩹 시간을 지정하지 않았을 경우 종료시점이라면 23시 59분 59초로 간주

src/entities/kanban.ts, src/infrastructures/createKanbanService.ts, src/infrastructures/createNotionKanbanClient.ts
=> ✨ due date 대신 schedule 필드로 변경

.github/workflows/kanban-check-script.yml
=> 💩 자동화 삽질 3

apps/kanban-check-script/src/clients/messengerClient.ts, apps/kanban-check-script/src/infrastructures/createKanbanService.ts, apps/kanban-check-script/src/infrastructures/createSlackMessengerClient.ts
resolved #40 
링크도 종속되지 않게 수정했습니다
=> ♻️ kanbanService 가 슬랙에 종속되지 않도록 리팩

apps/kanban-check-script/src/entities/member.ts, apps/kanban-check-script/src/infrastructures/createNotionKanbanClient.ts, apps/kanban-check-script/src/infrastructures/createSlackMessengerClient.ts
=> :busts_in_silhouette: add subeenpark-io

apps/kanban-check-script/src/infrastructures/createKanbanService.ts
=> ♻️ remove unnecessary reduce

apps/snutt-admin-web/src/app/App.svelte, apps/snutt-admin-web/src/app/components/Button.svelte, apps/snutt-admin-web/src/app/components/Checkbox.svelte, apps/snutt-admin-web/src/app/components/Input.svelte, apps/snutt-admin-web/src/app/components/Select.svelte, apps/snutt-admin-web/src/app/contexts/ServiceContext.ts, apps/snutt-admin-web/src/app/pages/PushNotificationPage/index.svelte, apps/snutt-admin-web/src/clients/ApiClient.ts, apps/snutt-admin-web/src/entities/PushNotification.ts, apps/snutt-admin-web/src/infrastructures/createFetchClient.ts, apps/snutt-admin-web/src/infrastructures/createPushNotificationRepository.ts, apps/snutt-admin-web/src/infrastructures/createPushNotificationService.ts, apps/snutt-admin-web/src/main.ts, apps/snutt-admin-web/src/repositories/PushNotificationRepository.ts, apps/snutt-admin-web/src/services/PushNotificationService.ts
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1702191385980379
https://www.notion.so/wafflestudio/caeecf95614448d895d9c887e97779a8?pvs=4
=> ✨ 푸시 기능 추가

crons/kanban-dashboard/src/infrastructures/createKanbanService.ts, packages/infrastructures/src/createSlackMessengerPresenter.ts
=> ✨ 칸반 대시보드 구현

crons/kanban-dashboard/src/infrastructures/createKanbanService.ts, packages/adapters/src/messengerPresenter.ts, packages/infrastructures/src/createSlackMessengerPresenter.ts
=> ✨ 대시보드 슬랙 메시지에 이모지 추가

apps/snutt-admin-web/src/infrastructures/createPushNotificationService.ts
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1702998034555509?thread_ts=1702192831.758879&cid=C0PAVPS5T
=> 🚑 urlScheme -> url_scheme

crons/kanban-reporter/src/infrastructures/createKanbanService.ts, packages/adapters/src/kanbanRepository.ts, packages/infrastructures/src/createNotionKanbanRepository.ts
https://www.notion.so/wafflestudio/537e2ef2be074704b713b775590f7aec?pvs=4 이거 작업하려고 보니 [notion query](https://developers.notion.com/reference/post-database-query-filter#date) 가 너무 제한적이어서, 그냥 다 불러와서 클라이언트 사이드에서 처리하도록 합니다.
=> ♻️ notion query 대신 다 불러와서 클라이언트에서 쿼리하도록 변경

.github/workflows/kanban-weekly-summary.yml, crons/kanban-reporter/package.json, crons/kanban-reporter/src/index.ts, crons/kanban-reporter/src/infrastructures/createKanbanService.ts, crons/kanban-reporter/src/services/kanbanService.ts, packages/adapters/src/messengerPresenter.ts, packages/entities/src/kanban.ts, packages/infrastructures/src/createSlackMessengerPresenter.ts
https://www.notion.so/wafflestudio/537e2ef2be074704b713b775590f7aec?pvs=4
=> ✨ weekly summary 보내는 기능 구현

packages/infrastructures/src/createNotionKanbanRepository.ts
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1704118018850099?thread_ts=1704117501.534609&cid=C0PAVPS5T
=> 👽 part all 추가된 것 반영

crons/kanban-reporter/src/infrastructures/createKanbanService.ts
=> 💬 포매팅 살짝 변경

.github/workflows/kanban-dashboard.yml, .github/workflows/kanban-issue-checker.yml, .github/workflows/kanban-weekly-summary.yml, README.md, crons/kanban-reporter/src/index.ts, crons/kanban-reporter/src/infrastructures/createKanbanService.ts, packages/adapters/src/kanbanRepository.ts, packages/entities/src/kanban.ts, packages/infrastructures/src/createNotionKanbanRepository.ts, packages/infrastructures/tsconfig.json
https://www.notion.so/wafflestudio/47f64e45f8694a2dae361d27cf9ea6b4?pvs=4
=> ✨ 스크럼 도우미가 파트가 아닌 에픽 기준으로 알려준다

.github/workflows/kanban-dashboard.yml, .github/workflows/kanban-issue-checker.yml
01/31 scrum 결정사항
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1706662804790499
=> ✨ 칸반일정봇 시간 변경

.github/workflows/deploy-notifier.yml, apps/deploy-notifier/src/index.ts
=> ✏️ 토큰 시크릿 이름 변경

.github/workflows/deploy-notifier.yml, .github/workflows/dispatch-github-release-deploy-notifier.yml, apps/deploy-notifier/src/index.ts, apps/deploy-notifier/src/infrastructures/implementGithubReleaseNoteRepository.ts, apps/deploy-notifier/src/infrastructures/implementNotifyService.ts
https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
=> ✨ reusable workflow

apps/snutt-admin-web/src/app/App.svelte, apps/snutt-admin-web/src/app/components/ConfirmRequiredButton.svelte, apps/snutt-admin-web/src/app/components/Header.svelte, apps/snutt-admin-web/src/app/pages/LoginPage/index.svelte, apps/snutt-admin-web/src/app/pages/PushNotificationPage/index.svelte, apps/snutt-admin-web/src/entities/PersistStorage.ts, apps/snutt-admin-web/src/infrastructures/createAuthRepository.ts, apps/snutt-admin-web/src/infrastructures/createAuthService.ts, apps/snutt-admin-web/src/infrastructures/createHtmlDocumentThemeRepository.ts, apps/snutt-admin-web/src/infrastructures/createPushNotificationRepository.ts, apps/snutt-admin-web/src/infrastructures/createPushNotificationService.ts, apps/snutt-admin-web/src/repositories/AuthRepository.ts, apps/snutt-admin-web/src/repositories/PushNotificationRepository.ts, apps/snutt-admin-web/src/repositories/ThemeRepository.ts, apps/snutt-admin-web/src/services/AuthService.ts, apps/snutt-admin-web/src/services/PushNotificationService.ts, apps/snutt-admin-web/vite.config.ts
푸시 나에게만 쏘기를 구현합니다. 나에게만 쏘기일 경우 버튼 클릭 시 컨펌을 패스합니다.
dev or local 일 경우 자동로그인을 지원합니다. prod 는 자동로그인 안됩니다.
=> ✨ 푸시 나에게만 쏘기, dev/local 자동로그인구현

apps/kanban-reporter/src/infrastructures/createKanbanService.ts, packages/adapters/src/messengerPresenter.ts, packages/entities/src/kanban.ts, packages/entities/src/member.ts, packages/infrastructures/src/createNotionKanbanRepository.ts, packages/infrastructures/src/createSlackMessengerPresenter.ts
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1712323534139969?thread_ts=1712323415.292309&cid=C0PAVPS5T
=> 🧑‍💻 멤버 매핑정보 없는 경우와 PM이 없는 에픽 대응, 이슈 없으면 이슈봇 안보내도록 수정

apps/kanban-reporter/src/services/kanbanService.ts
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1716357263130819?thread_ts=1716342073.376669&cid=C0PAVPS5T
=> ✨ 진행상황 없는 에픽은 띄우지 않는다

.github/workflows/kanban-dashboard.yml, .github/workflows/kanban-issue-checker.yml, .github/workflows/kanban-weekly-summary.yml
=> 노션 API 토큰 재발급

apps/kanban-reporter/src/entities/member.ts, apps/kanban-reporter/src/infrastructures/createNotionKanbanRepository.ts, apps/kanban-reporter/src/infrastructures/createSlackMessengerPresenter.ts
=> add @qdrptd
